---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-sync-b2
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: kopia-sync-b2-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        BUCKET: "{{ .VOLSYNC_KOPIA_B2_BUCKET_NAME }}"
        ENDPOINT: "s3.narden.au"
        ACCESS_KEY: "{{ .VOLSYNC_KOPIA_B2_ACCESS_KEY }}"
        SECRET_KEY: "{{ .VOLSYNC_KOPIA_B2_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: /kopia
    - extract:
        key: /backblaze