---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret sparkyfitness-secret
spec:   
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        # Database Configuration
        SPARKY_FITNESS_DB_NAME: &dbName sparkyfitness
        SPARKY_FITNESS_DB_USER: postgres
        SPARKY_FITNESS_DB_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        SPARKY_FITNESS_DB_HOST: &dbHost postgres17-rw.database.svc.cluster.local
        SPARKY_FITNESS_DB_PORT: "5432"
        SPARKY_FITNESS_APP_DB_USER: &dbUser sparkyfitness
        SPARKY_FITNESS_APP_DB_PASSWORD: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Application Configuration
        SPARKY_FITNESS_FRONTEND_URL: "https://fitness.narden.au"
        SPARKY_FITNESS_SERVER_HOST: "sparkyfitness-server.home"
        SPARKY_FITNESS_SERVER_PORT: "3010"
        SPARKY_FITNESS_LOG_LEVEL: "INFO"
        SPARKY_FITNESS_DISABLE_SIGNUP: "{{ .SPARKY_FITNESS_DISABLE_SIGNUP }}"
        SPARKY_FITNESS_ADMIN_EMAIL: "{{ .SPARKY_FITNESS_ADMIN_EMAIL }}"
        SPARKY_FITNESS_FORCE_EMAIL_LOGIN: "true"
        # Environment Configuration
        NODE_ENV: "production"
        TZ: "Australia/Sydney"
  dataFrom:
    - extract:
        key: /sparkyfitness
    - extract:
        key: /cloudnative-pg