---
connectivity:
  checker:
    target: 172.20.24.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.narden.au
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover

metrics: true


storage:
  type: sqlite
  path: ${GATUS_CONFIG_PATH}/sqlite.db
  caching: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/27022259
  link: https://github.com/philgood
  buttons:
    - name: Github
      link: https://github.com/philgood
    - name: Homelab
      link: https://github.com/philgood/home-ops

alerting:
  pushover:
    application-token: ${CUSTOM_PUSHOVER_APP_TOKEN}
    user-key: ${CUSTOM_PUSHOVER_USER_KEY}
    priority: 1
    resolved-priority: 0
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 3

web:
  port: ${GATUS_WEB_PORT}
