---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamateapi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: teslamateapi-secret
    template:
      engineVersion: v2
      data:
        # App
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        DATABASE_HOST: &dbHost postgres17-rw.database.svc.cluster.local
        DATABASE_NAME: &dbName teslamate
        DATABASE_USER: &dbUser "{{ .TESLA_POSTGRES_USER }}"
        DATABASE_PASS: &dbPass "{{ .TESLA_POSTGRES_PASS }}"
        API_TOKEN: "{{ .TESLAMATEAPI_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER_FLAGS: "-s"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # mqtt
        MQTT_HOST: mosquitto.automation.svc.cluster.local
        MQTT_USERNAME: "{{ .MQTT_USERNAME }}" 
        MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: /teslamate
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /mqtt