metadata_dir = "/meta"
data_dir = "/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"
replication_factor = 1
compression_level = 2
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "garage.storage.svc.cluster.local:3901"

[s3_api]
s3_region = "eu-west-1"
api_bind_addr = "[::]:3900"
root_domain = ".s3.narden.au"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.narden.au"

[admin]
api_bind_addr = "[::]:3903"