# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./podmonitor.yaml
components:
  - ../../../../components/volsync
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: home-assistant-tesla-key
    files:
      - com.tesla.3p.public-key.pem=./tesla-public-key.pem