---
ingress:
  - hostname: "*.narden.au"
    service: https://envoy-external.network.svc.cluster.local
    originRequest:
      http2Origin: true
      originServerName: external.narden.au
  - service: http_status:404
