# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./garage/ks.yaml
  - ./dragonfly/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
  - ./kopia/ks.yaml
  - ./syncthing/ks.yaml
